### ISSUE TITLE
Some chunks do not render properly after updating from 1.0.2 to 1.0.3 on server install

### ISSUE THREAD

**Issue by SmallSansSerif** [VazkiiMods/Bliss#138]
### Bliss version

1.0.3 Server

### The latest.log file

client log already given on Discord

### Issue description

Update 1.0.2 world on server to 1.0.3 world and chunks fail to render or load in certain areas. Also, client crashes occur when near these areas.

![2022-06-22_17 06 12](https://user-images.githubusercontent.com/4984139/175301875-b4e15f44-c410-4165-b8e7-c0bab4f89fb4.png)
![2022-06-22_17 10 19](https://user-images.githubusercontent.com/4984139/175301880-b88c9b2e-3677-4054-9507-13a65caabf6e.png)
![2022-06-22_17 15 11](https://user-images.githubusercontent.com/4984139/175301884-87fa2d7c-2125-48f5-914d-a5dcbb44fe3f.png)
![2022-06-22_17 49 02](https://user-images.githubusercontent.com/4984139/175301886-78135f08-da31-409d-aa29-f851cf06cda1.png)
![2022-06-22_17 49 13](https://user-images.githubusercontent.com/4984139/175301893-112329ca-56b8-4ee7-ae95-a59ad69ce05b.png)
![2022-06-22_17 49 29](https://user-images.githubusercontent.com/4984139/175301896-5e2806b3-0717-446f-b451-d27fb7161a3e.png)

### Steps to reproduce

Update 1.0.2 world on server to 1.0.3 world.

**Comment by SmallSansSerif** [comment]
Tried to update to 1.0.4 and client crashes still in this area. 

[crash-2022-07-07_20.00.58-client.txt](https://github.com/VazkiiMods/Bliss/files/9067953/crash-2022-07-07_20.00.58-client.txt)

Description: Unexpected error

java.lang.NoSuchMethodError: 'int biomesoplenty.core.ClientProxy.getRainbowBirchColor(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos)'

**Comment by SmallSansSerif** [comment]
It's a client crash and visual glitch when Compatoplenty rainbow hedges are used above the 1.0.2 version of Bliss. Switched all the compatoplenty hedges to a non-rainbow variant and the chunks and hedges load fine.
